<a href="https://colab.research.google.com/github/mukilarasiu2025cse/FUNDAMENTAL-OF-DATA-SCIENCE-CS23334/blob/main/Reg_No_250701457_Name_Mukil_Arasi_U_Exp_No_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
import pandas as pd

# Experiment No. 11: Pandas DataFrame

# Create DataFrame
list1 = [[1, 'Smith', 50000],
         [2, 'Jones', 60000]]

df1 = pd.DataFrame(list1)
display(df1)

df1.columns = ['Empd', 'Name', 'Salary']
display(df1)
df1.info()

# Employee dataset
df = pd.DataFrame({
    'emp id': [1, 2, 3, 4, 5, 6, 7],
    'name ': [
        'SREE VARSSINI K S',
        'SREEMATHI B',
        'SREYA G',
        'SREYASKARI MULLAPUDI',
        'SRI AKASH U G',
        'SRI HARSHAVARDHANAN R',
        'SRI HARSHAVARDHANAN R'
    ],
    'salary': [5000, 6000, 7000, 5000, 8000, 3000, 6000]
})

# Display first and last five rows
display(df.head())
display(df.tail())

# DataFrame information
df.info()

# Salary column
display(df.salary)
print(type(df.salary))

# Statistical calculations
print("Mean:", df.salary.mean())
print("Median:", df.salary.median())
print("Mode:")
display(df.salary.mode())

print("Variance:", df.salary.var())
print("Standard Deviation:", df.salary.std())

# Statistical descriptions
display(df.describe())
display(df.describe(include='all'))

# Columns
empCol = df.columns
print(empCol)

# Convert DataFrame to NumPy array
emparray = df.values
print(emparray)

# Convert array back to DataFrame
employee_DF = pd.DataFrame(emparray, columns=empCol)
display(employee_DF)

print("Experiment No. 11 completed successfully!")

   0      1      2
0  1  Smith  50000
1  2  Jones  60000

   Empd   Name  Salary
0     1  Smith   50000
1     2  Jones   60000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Empd    2 non-null      int64
 1   Name    2 non-null      object
 2   Salary  2 non-null      int64
dtypes: int64(2), object(1)
memory usage: 180.0+ bytes

   emp id                 name   salary
0       1     SREE VARSSINI K S    5000
1       2           SREEMATHI B    6000
2       3               SREYA G    7000
3       4  SREYASKARI MULLAPUDI    5000
4       5         SRI AKASH U G    8000

   emp id                  name   salary
2       3                SREYA G    7000
3       4   SREYASKARI MULLAPUDI    5000
4       5          SRI AKASH U G    8000
5       6  SRI HARSHAVARDHANAN R    3000
6       7  SRI HARSHAVARDHANAN R    6000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   emp id  7 non-null      int64
 1   name    7 non-null      object
 2   salary  7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

0    5000
1    6000
2    7000
3    5000
4    8000
5    3000
6    6000
Name: salary, dtype: int64

<class 'pandas.core.series.Series'>
Mean: 5714.285714285715
Median: 6000.0
Mode:

0    5000
1    6000
Name: salary, dtype: int64

Variance: 2571428.5714285714
Standard Deviation: 1603.5674514745463

         emp id       salary
count  7.000000     7.000000
mean   4.000000  5714.285714
std    2.160247  1603.567451
min    1.000000  3000.000000
25%    2.500000  5000.000000
50%    4.000000  6000.000000
75%    5.500000  6500.000000
max    7.000000  8000.000000

          emp id                  name        salary
count   7.000000                      7     7.000000
unique       NaN                      6          NaN
top          NaN  SRI HARSHAVARDHANAN R          NaN
freq         NaN                      2          NaN
mean    4.000000                    NaN  5714.285714
std     2.160247                    NaN  1603.567451
min     1.000000                    NaN  3000.000000
25%     2.500000                    NaN  5000.000000
50%     4.000000                    NaN  6000.000000
75%     5.500000                    NaN  6500.000000
max     7.000000                    NaN  8000.000000

Index(['emp id', 'name ', 'salary'], dtype='object')
[[1 'SREE VARSSINI K S' 5000]
 [2 'SREEMATHI B' 6000]
 [3 'SREYA G' 7000]
 [4 'SREYASKARI MULLAPUDI' 5000]
 [5 'SRI AKASH U G' 8000]
 [6 'SRI HARSHAVARDHANAN R' 3000]
 [7 'SRI HARSHAVARDHANAN R' 6000]]

  emp id                  name  salary
0      1      SREE VARSSINI K S   5000
1      2            SREEMATHI B   6000
2      3                SREYA G   7000
3      4   SREYASKARI MULLAPUDI   5000
4      5          SRI AKASH U G   8000
5      6  SRI HARSHAVARDHANAN R   3000
6      7  SRI HARSHAVARDHANAN R   6000

Experiment No. 11 completed successfully!